package cmd

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"log"
  "io"
	"os/exec"
  "path/filepath"
	"text/template"
	"strings"
	"github.com/spf13/cobra"
)

type CommitDetail struct {
	Hash    string   `json:"hash"`
	Author  string   `json:"author"`
  Date    string   `json:"date"`
	Summary string   `json:"summary"`
	Files   []string `json:"files"`
}

// The structure we want Ollama to return
type ChangelogData struct {
	Version  string         `json:"version"`
	Date     string         `json:"date"`
	Features []CommitDetail `json:"features"`
	Fixes    []CommitDetail `json:"fixes"`
	Breaking []CommitDetail `json:"breaking"`
}

// The template you can customize without touching the AI prompt
const mdTemplate = `
# Release {{.Version}} ({{.Date}})

{{if .Features}}## 🚀 New Features
{{range .Features -}}
{{if .Summary}}- **{{.Summary}}** *by {{.Author}}* ({{.Date}} - {{.Hash}})
  {{if .Files}}*Files:* ` + "`" + `{{join .Files ", "}}` + "`" + `{{end}}{{end}}
{{end}}{{end}}
{{if .Fixes}}## 🐛 Bug Fixes
{{range .Fixes -}}
{{if .Summary}}- **{{.Summary}}** ({{.Date}}) — {{.Author}} [{{.Hash}}]{{end}}
{{end}}{{end}}
{{if .Breaking}}## ⚠️ Breaking Changes
{{range .Breaking -}}
{{if .Summary}}- **{{.Summary}}** ({{.Date}}) — {{.Author}} [{{.Hash}}]{{end}}
{{end}}{{end}}
---
*Generated by git-back* 2026 (c) [CLZ](https://cmdlinezero.dev)`


var (
  isLongForm bool
  versionStr string
	targetSHA string
)

func init() {
  // Attach the main 'gen' command to the root
  rootCmd.AddCommand(genCmd) 
    
  // Attach the DIFFERENT 'changelog' command to 'gen'
  genCmd.AddCommand(changelogCmd) 

	// Add the flag to the changelog subcommand
	changelogCmd.Flags().StringVarP(&targetSHA, "sha", "s", "HEAD", "The specific commit SHA to analyze")
	changelogCmd.Flags().BoolVarP(&isLongForm, "long", "l", false, "Use long form git log with file statuses")
  changelogCmd.Flags().StringVarP(&versionStr, "version", "v", "v1.0.0", "Version number for the header")
}


var genCmd = &cobra.Command{
	Use:   "gen",
	Short: "Generate documentation from git history",
}

var changelogCmd = &cobra.Command{
	Use:   "changelog",
	Short: "Generate a Markdown changelog",
	Run: func(cmd *cobra.Command, args []string) {
		var gitArgs []string

    // 1. Get the current short SHA for the filename regardless of mode
    shaCmd := exec.Command("git", "rev-parse", "--short", targetSHA)
    shaOut, err := shaCmd.Output()
    if err != nil {
        fmt.Println("❌ Error: Could not resolve git SHA. Are you in a git repo?")
        return
    }

    shortSHA := strings.TrimSpace(string(shaOut))
    fileName := fmt.Sprintf("git-%s.md", shortSHA)

    // 1. Determine the Git Command & Filename
    if targetSHA != "" && targetSHA != "HEAD" {
        // POINT MODE: Target one specific commit
        fmt.Printf("🎯 Analyzing specific commit: %s\n", targetSHA)
        gitArgs = []string{
            "show", 
            targetSHA, 
            "--pretty=format:---%nHash: %h%nAuthor: %an%nDate: %as%nMessage: %s", 
            "--name-status",
        }

        fileName = fmt.Sprintf("changes-%s.md", targetSHA)
    } else {
        fmt.Printf("📜 Generating summary for HEAD (%s)...\n", shortSHA)
        // Use your existing log logic here
        if isLongForm {
            gitArgs = []string{"log", "-n", "5", "--pretty=format:---%nHash: %h%nAuthor: %an%nDate: %as%nMessage: %s", "--name-status"}
        } else {
            gitArgs = []string{"log", "-n", "10", "--pretty=format:---%nHash: %h%nAuthor: %an%nDate: %as%nMessage: %s", "--name-status"}
        }
    }

		logs, err := exec.Command("git", gitArgs...).Output()
		if err != nil {
			fmt.Println("❌ Error fetching git logs:", err)
			return
		}

    fmt.Println("🤖 Extracting structured data from logs...")
		data := askOllamaForJSON(string(logs))

    if data == nil { return }

    if versionStr != "" {
        data.Version = versionStr
    }

    // Populate the Template
		tmpl, _ := template.New("changelog").
		  Funcs(template.FuncMap{"join": strings.Join}).
		  Parse(mdTemplate)
		
		var buf bytes.Buffer
		err = tmpl.Execute(&buf, data)
		if err != nil {
			fmt.Println("❌ Template error:", err)
			return
		}

		changelogDir := "changelog"

		// Create the directory if it doesn't exist (Perm 0755 is standard for rwxr-xr-x)
		if err := os.MkdirAll(changelogDir, 0755); err != nil {
			log.Fatalf("Failed to create %s directory: %v", changelogDir, err)
		}

		os.WriteFile(fileName, buf.Bytes(), 0644)
		fmt.Printf("✨ Generated: %s for target SHA %s.\n", filepath.Base(fileName), targetSHA)
	},
}

func askOllamaForJSON(logs string) *ChangelogData {
  // Use externalized config
	// url := "http://localhost:11434/api/generate"
	url := AppConfig.Ollama.URL + "/api/generate"
	model := AppConfig.Ollama.Model

	
  prompt := `You are a release note architect. Analyze the following Git logs and 
    output ONLY a JSON object. 

    RULES:
    1. Categorize "feat" or "Add" as features, "fix" as fixes.
    2. If a commit message is a Merge or generic, put it in features or ignore it.
    3. The "summary" should be a clean version of the commit message.
    4. The "date" must be extracted from the 'Date:' line in the logs.
    5. Do not leave fields empty. If unknown, use "Recent".

    LOGS:
    ` + logs + `

    JSON STRUCTURE:
    {
      "version": "v1.0.0",
      "date": "2026-03-20",
      "features": [{"hash": "", "author": "", "date": "", "summary": "", "files": []}],
      "fixes": [],
      "breaking": []
    }`

	// payload, _ := json.Marshal(map[string]interface{}{
	// 	"model":  "gemma3:latest",
	// 	"prompt": prompt,
	// 	"format": "json", // important: forces ollama to output valid json
	// 	"stream": false,
	// })

  payload, _ := json.Marshal(map[string]interface{}{
  		"model":  model,
  		"prompt": prompt,
  		"format": "json", // important: forces ollama to output valid json
  		"stream": false,
  })

	resp, _ := http.Post(url, "application/json", bytes.NewBuffer(payload))
  if resp.StatusCode != http.StatusOK {
      body, _ := io.ReadAll(resp.Body)
      fmt.Printf("❌ Ollama Error (%d): %s\n", resp.StatusCode, string(body))
      return nil
  }
	defer resp.Body.Close()

	var res struct{ Response string }
	json.NewDecoder(resp.Body).Decode(&res)

	// DEBUG PRINT: See what the AI actually said
	fmt.Println("--- DEBUG: AI Raw Response ---")
	fmt.Println(res.Response)
	fmt.Println("------------------------------")
	
	// Parse the string response into our Go struct
	var data ChangelogData
	err := json.Unmarshal([]byte(res.Response), &data)
	if err != nil {
		    fmt.Printf("❌ JSON Parse Error: %v\n", err)
	}
	return &data
}

func askOllamaForMarkdown(logs string, detailed bool) string {
	url := "http://localhost:11434/api/generate"
	
	systemPrompt := "You are a technical writer. Summarize these git logs into a clean Markdown changelog."
	if detailed {
		systemPrompt += " Use the file change information to explain *what* parts of the system were affected."
	}

	prompt := fmt.Sprintf("%s\n\nLOGS:\n%s", systemPrompt, logs)

	payload, _ := json.Marshal(map[string]interface{}{
		"model":  "llama3",
		"prompt": prompt,
		"stream": false,
	})

	resp, err := http.Post(url, "application/json", bytes.NewBuffer(payload))
	if err != nil {
		return "Error: Ollama connection failed."
	}
	defer resp.Body.Close()

	var res struct{ Response string }
	json.NewDecoder(resp.Body).Decode(&res)
	return res.Response
}
